[package]
name = "actix-web-flash"
version = "0.1.0"
authors = ["Hans Ole Hatzel <hhatzel@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
time = "0.1"
